### ISSUE TITLE
[Android] - Claiming a QR Code Deletes all previously saved Certificates

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-android#80] opened 2021-07-15 09:12 UTC
## Describe the bug
Upon claiming the following QR Code, all previously saved certificates got deleted.

The logs are attached.  The event happaned around 10:29 o'clock, 15.07.22.

Initial state:  one or more certificates are already claimed and successfully saved on device
Step 1: Scan attached Code
Step 2: Type in Tan 
Step 3: Press save  -- > the screen "No certificate available is shown" (attached Image)

## Observed Behavior
After saving all previously saved certificates are deleted and no certificate is saved.

## Additional Info
Furthermore,  once in this state -- no other certificate can be saved any more on the device.

## Expected behaviour

Certificate is successfully saved additionally to the rest of previously saved certificates.

## Technical details
Wallet App 1.1.0-tst
Galaxy XCover 4, Android 9

## Logs
[logcat.txt](https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/files/6821839/logcat.txt)

![Liem_Rec_abgelaufen](https://user-images.githubusercontent.com/76050122/125762402-b276ba4f-d45c-425d-832a-c168ccbcc959.png)

**Comment by kerstin-oppermann-tsi** [comment] 2021-07-15 09:38
@RalicaY please provide the logs for the developers.

For my side all works fine, I claimed 4 certificates with the 1.1.0 -tst app.

**Comment by RalicaY** [comment] 2021-07-15 09:40
@kerstin-oppermann-tsi , yes the problem seems to be sporadic, so this is why I have attached the logs. Alsp, I could observe it three times so far with seemingly normal codes while @ltranvan can generate specific codes which consistently lead to the bug manifestation.

**Comment by kerstin-oppermann-tsi** [comment] 2021-07-15 09:44
@RalicaY my fault, I didnt see the logs. But now I looked at it and yes there is an error inside, maybe that can help the developers to find the matter with this fact.

**Comment by kerstin-oppermann-tsi** [comment] 2021-07-15 10:10
@oleksandrsarapulovgl every time I claim a REC certificate that is only valid till the actual day (in that case till today 15th of july) all other certificates will be delete in the app. In the further steps no caliming of certificates is possible. I have to deinstall and reinstall the app.

**Comment by oleksandrsarapulovgl** [comment] 2021-07-15 13:09
@kerstin-oppermann-tsi @RalicaY thank you for your work here! Just a follow up on the issue. I found the root cause - certificates are not deleted, but not displayed, because during preparing data for displaying application catches exception: "java.lang.IllegalArgumentException: Expiration is before current time: 2021-07-15T00:00:00Z".

@kerstin-oppermann-tsi  could you please clarify: do we just ignore such cases, and display certificates silently?

FYI: @Hendrik-Schmidt-Schierhorn-TSI

**Comment by ltranvan** [comment] 2021-07-15 14:01
I think that 
a.)- the certificates should be displayed, specially for those which are already claimed
and b.)- in the spec it is not forbidden to claim an expired certificate for a private person in his personal Wallet App.

**Comment by kerstin-oppermann-tsi** [comment] 2021-07-15 14:07
@oleksandrsarapulovgl yes, I think what @ltranvan wrote is correct, so we will display expired certificates too. Its my own wallet app and within I can check if my claimed certificate is valid (for countries) or not.

**Comment by kerstin-oppermann-tsi** [comment] 2021-07-16 16:02
fixed in release 1.1.1.

**Closed by kerstin-oppermann-tsi** 2021-07-16 16:02 UTC
Labels: bug
